---
# Source: common/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-test
  labels:
    helm.sh/chart: common-11.7.0
    app.kubernetes.io/name: common
    app.kubernetes.io/instance: common
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: common
      app.kubernetes.io/instance: common
  template:
    metadata:
      labels:
        app.kubernetes.io/name: common
        app.kubernetes.io/instance: common
    spec:
      imagePullSecrets:
      serviceAccountName: configmap-test
      containers:
      - name: common
        image: nginx:latest
        imagePullPolicy: Always
        
        envFrom:
          - configMapRef:
              name: first-configmap
          - configMapRef:
              name: second-configmap
        
        resources:
            null
