---
# Source: common/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-test
  labels:
    helm.sh/chart: common-11.7.0
    app.kubernetes.io/name: common
    app.kubernetes.io/instance: common
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
